# Generated by Django 5.0.3 on 2024-04-24 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Toursite', '0005_cities_flightsintours_tourdescription_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='сities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_city', models.CharField(db_column='Name_city', max_length=100)),
                ('City_id', models.CharField(db_column='City_id', max_length=3)),
            ],
        ),
        migrations.RemoveField(
            model_name='flightsintours',
            name='city',
        ),
        migrations.DeleteModel(
            name='Cities',
        ),
        migrations.DeleteModel(
            name='FlightsInTours',
        ),
    ]
