# Generated by Django 5.0.3 on 2024-04-24 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Toursite', '0007_rename_сities_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='City_id',
            field=models.IntegerField(db_column='City_id', max_length=3),
        ),
        migrations.AlterModelTable(
            name='city',
            table='cities',
        ),
    ]
