# Generated by Django 5.0.3 on 2024-04-24 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Toursite', '0008_alter_city_city_id_alter_city_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'managed': False},
        ),
    ]
