# Generated by Django 5.0.3 on 2024-04-24 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Toursite', '0011_alter_city_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={},
        ),
    ]
