# Generated by Django 5.0.3 on 2024-04-25 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Toursite', '0013_alter_city_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='flights_in_tours',
            fields=[
                ('Flights_in_tours_id', models.AutoField(db_column='flights_in_tours_id', primary_key=True, serialize=False)),
                ('City_id', models.IntegerField(db_column='City_id', max_length=100)),
                ('Day_number_in_city', models.IntegerField(db_column='day_number_in_city', max_length=100)),
                ('Tour_number_id', models.IntegerField(db_column='tour_number_id', max_length=100)),
            ],
            options={
                'db_table': 'flights_in_tours',
                'managed': False,
            },
        ),
    ]
