# Generated by Django 5.0.3 on 2024-04-30 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Toursite', '0014_flights_in_tours'),
    ]

    operations = [
        migrations.CreateModel(
            name='aircraft',
            fields=[
                ('aircraft_id', models.IntegerField(db_column='aircraft_id', primary_key=True, serialize=False)),
                ('name', models.TextField(db_column='name')),
                ('seats_number', models.IntegerField(db_column='seats_number')),
            ],
            options={
                'db_table': 'aircraft',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='airline',
            fields=[
                ('airlines_id', models.IntegerField(db_column='airlines_id', primary_key=True, serialize=False)),
                ('airlines', models.TextField(db_column='airlines')),
            ],
            options={
                'db_table': 'airlines',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='connect_tours_wfs',
            fields=[
                ('tour_number_id', models.IntegerField(db_column='tour_number_id')),
                ('WFS_id', models.IntegerField(db_column='WFS_id')),
                ('number', models.IntegerField(db_column='number', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'connect_tours_wfs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='flight_shedule',
            fields=[
                ('flight_id', models.IntegerField(db_column='flight_id', primary_key=True, serialize=False)),
                ('date', models.DateField(db_column='date')),
                ('tickets_number', models.IntegerField(db_column='tickets_number')),
                ('WFS_id', models.IntegerField(db_column='WFS_id')),
                ('flight_number', models.IntegerField(db_column='flight_number')),
            ],
            options={
                'db_table': 'flight_schedule',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('Tour_id', models.IntegerField(db_column='Tour_id')),
                ('Flight_id', models.IntegerField(db_column='Flight_id')),
                ('date', models.DateField(db_column='date')),
                ('price', models.IntegerField(db_column='price')),
                ('Action', models.TextField(db_column='Action')),
                ('Operation_number', models.IntegerField(db_column='Operation_number', primary_key=True, serialize=False)),
                ('unique_order_number', models.IntegerField(db_column='unique_order_number')),
            ],
            options={
                'db_table': 'history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='tour_booking_history',
            fields=[
                ('tour_id', models.IntegerField(db_column='tour_id', primary_key=True, serialize=False)),
                ('number_people', models.IntegerField(db_column='number_people')),
                ('tour_order_number_id', models.IntegerField(db_column='tour_order_number_id')),
                ('action', models.CharField(db_column='action', max_length=45)),
                ('amount', models.IntegerField(db_column='amount')),
            ],
            options={
                'db_table': 'tour_booking_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WeeklyFlightSchedule',
            fields=[
                ('WFS_id', models.AutoField(db_column='WFS_id', primary_key=True, serialize=False)),
                ('week_day', models.TextField(db_column='week_day')),
                ('time', models.TextField(db_column='time')),
                ('price', models.IntegerField(db_column='price')),
                ('aircraft_id', models.IntegerField(db_column='aircraft_id')),
                ('departure_city_id', models.IntegerField(db_column='departure_city_id')),
                ('arrival_city_id', models.TextField(db_column='arrival_city_id')),
                ('airline_id', models.IntegerField(db_column='airline_id')),
                ('flight_duration', models.TextField(db_column='flight_duration')),
            ],
            options={
                'db_table': 'weekly_flight_schedule',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
        migrations.DeleteModel(
            name='Tour',
        ),
        migrations.DeleteModel(
            name='WeeklySchedule',
        ),
        migrations.DeleteModel(
            name='TourInfo',
        ),
        migrations.AlterModelOptions(
            name='tourdescription',
            options={'managed': False},
        ),
    ]
