# Generated by Django 5.0.3 on 2024-04-30 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Toursite', '0015_aircraft_airline_connect_tours_wfs_flight_shedule_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tourdescription',
            table='tour_description',
        ),
    ]
